//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthBusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabyrinthBusinessLogic.Properties.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can move backward or left..
        /// </summary>
        public static string BackwardOrLeftMovement {
            get {
                return ResourceManager.GetString("BackwardOrLeftMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can move backward or right..
        /// </summary>
        public static string BackwardOrRightMovement {
            get {
                return ResourceManager.GetString("BackwardOrRightMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can only move forward from here..
        /// </summary>
        public static string ForwardOnlyMovement {
            get {
                return ResourceManager.GetString("ForwardOnlyMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can move forward or backward..
        /// </summary>
        public static string ForwardOrBackwardMovement {
            get {
                return ResourceManager.GetString("ForwardOrBackwardMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can move forward or left..
        /// </summary>
        public static string ForwardOrLeftMovement {
            get {
                return ResourceManager.GetString("ForwardOrLeftMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can move forward or right..
        /// </summary>
        public static string ForwardOrRightMovement {
            get {
                return ResourceManager.GetString("ForwardOrRightMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player, you can move left or right..
        /// </summary>
        public static string LeftOrRightMovement {
            get {
                return ResourceManager.GetString("LeftOrRightMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is moving backward..
        /// </summary>
        public static string PlayerMovingBackward {
            get {
                return ResourceManager.GetString("PlayerMovingBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is moving forward..
        /// </summary>
        public static string PlayerMovingForward {
            get {
                return ResourceManager.GetString("PlayerMovingForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is moving left..
        /// </summary>
        public static string PlayerMovingLeft {
            get {
                return ResourceManager.GetString("PlayerMovingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is moving right..
        /// </summary>
        public static string PlayerMovingRight {
            get {
                return ResourceManager.GetString("PlayerMovingRight", resourceCulture);
            }
        }
    }
}
